[install]

whitelist = ["ilex-profile"]

[custom.all.ilex]
type = "local"
path = "."
ipkg = "ilex.ipkg"
test = "test/test.ipkg"

[custom.all.ilex-examples]
type = "local"
path = "examples"
ipkg = "ilex-examples.ipkg"

[custom.all.ilex-profile]
type = "local"
path = "profile"
ipkg = "profile.ipkg"
